<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVsxb6G\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVsxb6G/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVsxb6G.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVsxb6G\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXVsxb6G\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XVsxb6G',
    'container.build_id' => '42b5d1a7',
    'container.build_time' => 1568890994,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVsxb6G');
