<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MC5gLB5' shared service.

return $this->privates['.service_locator.MC5gLB5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController::show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController:show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
], [
    'App\\Controller\\ProductController::delete' => '?',
    'App\\Controller\\ProductController::edit' => '?',
    'App\\Controller\\ProductController::index' => '?',
    'App\\Controller\\ProductController::show' => '?',
    'App\\Controller\\ProductController:delete' => '?',
    'App\\Controller\\ProductController:edit' => '?',
    'App\\Controller\\ProductController:index' => '?',
    'App\\Controller\\ProductController:show' => '?',
]);
